In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder,StandardScaler,LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
import string, re

In [2]:
data = pd.read_csv('../Downloads/fake_job_postings.csv')

In [3]:
data.head()

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0
4,5,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0

Columns not needed:
job_id,
salary_range?

Text columns to combine:
title,
location,
department,
company_profile,
description,
requirements,
benefits,
employment_type,
required_experience,
required_education,
industry,
function

In [4]:
data.fillna(value=" ",inplace=True)

In [5]:
data['text']= data['title'] + ' ' + data['location'] + ' ' + data['department'] + ' ' + data['company_profile']+ ' ' + data['description'] + ' ' + data['requirements'] + ' ' + data['benefits']+ ' ' + data['employment_type'] + ' ' + data['required_experience']+' '+data['required_education']+ ' ' + data['industry'] + ' ' + data['function']

In [6]:
del data['title']
del data['location']
del data['department']
del data['company_profile']
del data['description']
del data['requirements']
del data['benefits']
del data['employment_type']
del data['required_experience']
del data['required_education']
del data['industry']
del data['function']
del data['job_id']
del data['salary_range']

In [7]:
data.head()

,telecommuting,has_company_logo,has_questions,fraudulent,text
0,0,1,0,0,"Marketing Intern US, NY, New York Marketing We..."
1,0,1,0,0,"Customer Service - Cloud Video Production NZ, ..."
2,0,1,0,0,"Commissioning Machinery Assistant (CMA) US, IA..."
3,0,1,0,0,"Account Executive - Washington DC US, DC, Wash..."
4,0,1,1,0,"Bill Review Manager US, FL, Fort Worth SpotS..."

In [8]:
stopwords_list = stopwords.words('english') + list(string.punctuation)

In [9]:
X=data.drop(columns=['fraudulent'])
y=data['fraudulent']
Xtrain,Xtest,ytrain,ytest = train_test_split(X,y)
Xtrain1,Xval,ytrain1,yval=train_test_split(Xtrain,ytrain)

In [10]:
tfidf= TfidfVectorizer(stop_words=stopwords_list)

In [11]:
Xtrans=pd.DataFrame(tfidf.fit_transform(Xtrain1['text']).toarray(),columns=tfidf.get_feature_names())

In [12]:
del Xtrain1['text']

In [13]:
XtrainTf= pd.concat([Xtrain1.reset_index(drop=True), Xtrans], axis=1)

In [14]:
XtrainTf

,telecommuting,has_company_logo,has_questions,00,000,0000,0001pt,0005,000aed,000applying,...,확고한,확보하고,확보했습니다,확장을,활용해,회계,회계관리,회사,ﬁber,ﬁnd
0,0,1,0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0,1,1,0.102221,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0,0,0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0,0,0,0.045596,0.033996,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0,1,0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10052,0,1,0,0.000000,0.104947,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10053,0,1,1,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10054,0,0,0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10055,0,1,0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10056,0,0,1,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense
from tensorflow.python.keras.layers import Dropout
from tensorflow.python.keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import KFold

In [16]:
model = Sequential()
model.add(Dense(len(XtrainTf.columns), input_dim=len(XtrainTf.columns), kernel_initializer='normal', activation='relu'))
model.add(Dense(200,activation='relu'))
model.add(Dense(1, activation='linear'))
model.summary()

WARNING:tensorflow:From /opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/initializers.py:143: calling RandomNormal.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:From /opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 75117)             5642638806
_________________________________________________________________
dense_1 (Dense)              (None, 200)               15023600
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 201
=================================================================
Total params: 5,657,662,607
Trainable params: 5,657,662,607
Non-trainable params: 0
_________________________________________________________________

In [17]:
model.compile(loss='mse', optimizer='adam', metrics=['mse','mae'])

In [ ]:
history = model.fit(XtrainTf, ytrain1, epochs=100, batch_size=3,  verbose=1, validation_split=0.2)

Train on 8045 samples, validate on 2012 samples

In [ ]:
nnpreds = []
for x in model.predict(Xtest):
    for x in x:
        nnpreds.append(x)

In [ ]:
abs(sum(ytest)-sum(nnpreds))/len(ytest)

In [ ]:
print(explained_variance_score(ytest,ypredtest))
# print(explained_variance_score(ytest,nnpreds))

In [ ]:
print(mean_absolute_error(ytest,ypredtest))
# print(mean_absolute_error(ytest,nnpreds))

In [ ]:
print(r2_score(ytest,ypredtest))
print(r2_score(ytest,nnpreds))

In [15]:
from sklearn.ensemble import RandomForestClassifier

In [16]:
rfr = RandomForestClassifier(n_estimators=1000,min_samples_split=5,min_samples_leaf=3,random_state=11)
rfr.fit(XtrainTf,ytrain1)
rfr.score(XtrainTf,ytrain1)

0.9782241225017401

In [17]:
yprebootstrapdtrain = rfr.predict(XtrainTf)
ypredtest = rfr.predict(Xtest)

ValueError: could not convert string to float: "Marketing and Administrative Assistant US, CA, Santa Monica     Making music is easier now than ever.Take out your phone. You will find an app to record, mix sound samples, or auto-tune your rap. Making music is not limited to the recording studio or classroom anymore. It happens all around us, every day. We are all musicians, in our own way.But what if you want to play with tunes atop the Billboard charts? Or learn your favorite Katy Perry song? Or jam on a Stevie Wonder classic?Enter Chromatik. We enable musicians - from pros to those playing their first notes - to learn, play, and share their favorite tunes. Our products are used by American Idol, Bruno Mars, the LAUSD, UCLA, and musicians around the globe.The Marketing and Administrative Assistant will support Chromatik's Marketing Team. The role is hands-on – you will write blog entries, manage social media accounts, pitch bloggers to generate coverage for Chromatik, and help come up with creative ideas to generate buzz and drive growth. ResponsibilitiesConceptualize, write, and schedule engaging marketing content that includes but is not limited to social media posts, blog posts, case studies, and email campaignsCoordinate marketing activities and opportunities to gather insights and deepen community engagementStay on top of evolving online trends regarding social media marketingTrack and measure programs to understand effectiveness and impactIdentify opportunities for public relations or earned-media exposureMaintain and replenish office inventory, anticipating supply needsMaintain office records and office efficiencyCoordinate for events such as company parties and open houses. This would include reserving facilities, if needed, catering, etc.Must havesA musical background! It doesn’t matter if it’s classical violin or heavy metal guitar. Chromatik is building the next-generation music education platform, and we expect that personal insights will help guide product development.Strong social presence and understanding of popular social platforms including but not limited to: Facebook, Twitter, Google , LinkedIn, YouTube, Instagram, Vine, PinterestBA in Marketing, PR, Communications, English, or related fieldDesirable, but not necessaryMusic transcription experience and familiarity with SibeliusBasic knowledge of Adobe Creative Suite The position is based in Santa Monica and includes full benefits, salary, and equity. \xa0 \xa0 Full-time   Bachelor's Degree Music Marketing"

In [ ]:
from sklearn.metrics import r2_score, explained_variance_score,mean_absolute_error,mean_squared_error
print(r2_score(ytrain,ypredtrain))
print(r2_score(ytest,ypredtest))